    mon-osd-node1:
         osd_dev:
            /dev/sdb
            /dev/sdc
    mon-osd-node2:
         osd_dev:
            /dev/sdb
            /dev/sdc
    mon-osd-node3:
         osd_dev:
            /dev/sdb
            /dev/sdc
