sudo salt salt-master ceph_sles.remove_pool .users.email
sudo salt salt-master ceph_sles.remove_pool .intent-log
sudo salt salt-master ceph_sles.remove_pool .usage
sudo salt salt-master ceph_sles.remove_pool .users.uid
sudo salt salt-master ceph_sles.remove_pool .rgw.control
sudo salt salt-master ceph_sles.remove_pool .users
sudo salt salt-master ceph_sles.remove_pool .log
sudo salt salt-master ceph_sles.remove_pool .rgw.gc
sudo salt salt-master ceph_sles.remove_pool .users.swift
sudo salt salt-master ceph_sles.remove_pool .rgw
